// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpjaVJggqe-da-qcI50ECx90gdoRyR2lA',
    appId: '1:995197251091:web:59b7f85baa91a957fed9e6',
    messagingSenderId: '995197251091',
    projectId: 'quizzoo-f8eb4',
    authDomain: 'quizzoo-f8eb4.firebaseapp.com',
    storageBucket: 'quizzoo-f8eb4.firebasestorage.app',
    measurementId: 'G-1JXXTKLW92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9U43BAm4nEW58rBptEOGm0trIxKQ4vxQ',
    appId: '1:995197251091:android:c01845d34b2ab94cfed9e6',
    messagingSenderId: '995197251091',
    projectId: 'quizzoo-f8eb4',
    storageBucket: 'quizzoo-f8eb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjG8kiKO7-0KkCBFAFJh9g8GlICjvOrBE',
    appId: '1:995197251091:ios:a60e99d0ffa313eefed9e6',
    messagingSenderId: '995197251091',
    projectId: 'quizzoo-f8eb4',
    storageBucket: 'quizzoo-f8eb4.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjG8kiKO7-0KkCBFAFJh9g8GlICjvOrBE',
    appId: '1:995197251091:ios:a60e99d0ffa313eefed9e6',
    messagingSenderId: '995197251091',
    projectId: 'quizzoo-f8eb4',
    storageBucket: 'quizzoo-f8eb4.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpjaVJggqe-da-qcI50ECx90gdoRyR2lA',
    appId: '1:995197251091:web:fd634bdac4f680f4fed9e6',
    messagingSenderId: '995197251091',
    projectId: 'quizzoo-f8eb4',
    authDomain: 'quizzoo-f8eb4.firebaseapp.com',
    storageBucket: 'quizzoo-f8eb4.firebasestorage.app',
    measurementId: 'G-JYTFW6P519',
  );
}
